image: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
options:
  max-time: 120

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

cypressChrome: &cypressChrome
  name: E2E tests on Chrome
  caches:
    - npm
    - node
    - cypress
  script:
    - cy:run:chrome
  artifacts:
    - cypress/screenshots/**
    - cypress/videos/**
    - cypress/downloads/**
    - cypress/test-results/**

cypressFirefox: &cypressFirefox
  name: E2E tests on Firefox
  caches:
    - npm
    - node
    - cypress
  script:
    - cy:run:firefox
  artifacts:
    - cypress/screenshots/**
    - cypress/videos/**
    - cypress/downloads/**
    - cypress/test-results/**

cypressEdge: &cypressEdge
  name: E2E tests on Edge
  caches:
    - npm
    - node
    - cypress
  script:
    - cy:run:edge
  artifacts:
    - cypress/screenshots/**
    - cypress/videos/**
    - cypress/downloads/**
    - cypress/test-results/**

pipelines:
  default:
    - step:
        name: Install dependencies and compile
        caches:
          - npm
          - cypress
          - node
        script:
          - yarn
          - yarn compile
          - yarn lint:fix
    - step:
        <<: *cypressChrome
